src/Entity/Recipe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 * @Vich\Uploadable()
 * @ORM\HasLifecycleCallbacks()
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string",length=255, nullable=true)
     */
    private $filename;

    /**
     * @var File
     * @Vich\UploadableField(mapping="recipe_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=2,minMessage="Au moin 2 caracteres")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $Preparation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User",inversedBy="recipes")
     * @ORM\JoinColumn()
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $time;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="recipesLiked")
     * @ORM\JoinTable(name="recipe_likes",
     *     joinColumns={@ORM\JoinColumn(name="recipe_id",referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="user_id",referencedColumnName="id")}
     *     )
     */
    private $likedBy;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rank",mappedBy="rankRecipe", cascade={"persist"}, orphanRemoval=true)
     */
    private $recipeRank;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingredient", mappedBy="recipe", cascade={"persist"}, orphanRemoval=true)
     */
    private $ingredient;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment",mappedBy="commentRecipe", cascade={"persist"}, orphanRemoval=true)
     */
    private $recipeComment;


    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function __construct()
    {
        $this->likedBy =new ArrayCollection();
        $this->recipeRank = new ArrayCollection();
        $this->ingredient = new ArrayCollection();
        $this->recipeComment = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPreparation(): ?string
    {
        return $this->Preparation;
    }

    public function setPreparation(string $Preparation): self
    {
        $this->Preparation = $Preparation;

        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * @param mixed $time
     * @return Recipe
     */
    public function setTime($time)
    {
        $this->time = $time;
        return $this;
    }

    /**
     * @ORM\PrePersist()
     */
    public function setTimeOnPersist():void
    {
        $this->time=new \DateTime();
    }

    /**
     * @return Collection
     */
    public function getLikedBy(): Collection
    {
        return $this->likedBy;
    }

    public function like(User $user)
    {
        if ($this->likedBy->contains($user))
        {
            return;
        }
        $this->likedBy->add($user);
    }

    /**
     * @return mixed
     */
    public function getRecipeRank()
    {
        return $this->recipeRank;
    }

    /**
     * @param mixed $recipeRank
     * @return Recipe
     */
    public function setRecipeRank($recipeRank)
    {
        $this->recipeRank = $recipeRank;
        return $this;
    }

    public function addLikedBy(User $likedBy): self
    {
        if (!$this->likedBy->contains($likedBy)) {
            $this->likedBy[] = $likedBy;
        }

        return $this;
    }

    public function removeLikedBy(User $likedBy): self
    {
        if ($this->likedBy->contains($likedBy)) {
            $this->likedBy->removeElement($likedBy);
        }

        return $this;
    }

    public function addRecipeRank(Rank $recipeRank): self
    {
        if (!$this->recipeRank->contains($recipeRank)) {
            $this->recipeRank[] = $recipeRank;
            $recipeRank->setRankRecipe($this);
        }

        return $this;
    }

    public function removeRecipeRank(Rank $recipeRank): self
    {
        if ($this->recipeRank->contains($recipeRank)) {
            $this->recipeRank->removeElement($recipeRank);
            // set the owning side to null (unless already changed)
            if ($recipeRank->getRankRecipe() === $this) {
                $recipeRank->setRankRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getIngredient(): Collection
    {
        return $this->ingredient;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredient->contains($ingredient)) {
            $this->ingredient[] = $ingredient;
            $ingredient->setRecipe($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        if ($this->ingredient->contains($ingredient)) {
            $this->ingredient->removeElement($ingredient);
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecipe() === $this) {
                $ingredient->setRecipe(null);
            }
        }

        return $this;
    }


    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Recipe
     */
    public function setFilename(?string $filename): Recipe
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Recipe
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Recipe
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getRecipeComment(): Collection
    {
        return $this->recipeComment;
    }

    /**
     * @param ArrayCollection $recipeComment
     * @return Recipe
     */
    public function setRecipeComment(ArrayCollection $recipeComment): Recipe
    {
        $this->recipeComment = $recipeComment;
        return $this;
    }





}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('Preparation')
            ->add('imageFile',FileType::class,[
                'required'=>true
            ])
        ;
        $builder->add('ingredient', CollectionType::class, [
            'entry_type' => IngredientType::class,
            'entry_options' => ['label' => false],
            'by_reference'       =>false,
            'allow_add'			=> true,
            'allow_delete'		=> true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Ingredient;
use App\Entity\IngredientSearch;
use App\Entity\Rank;
use App\Entity\Recipe;
use App\Entity\RecipeSearch;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\IngredientSearchType;
use App\Form\RankType;
use App\Form\RecipeSearchType;
use App\Form\RecipeType;
use App\Repository\IngredientRepository;
use App\Repository\RankRepository;
use App\Repository\RecipeRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;

/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{
    /**
     * @var ObjectManager
     */
    private $em;
    /**
     * @var RecipeRepository
     */
    private $repository;

    public function __construct(RecipeRepository $repository)
    {
        $this->repository = $repository;
//        $this->em = $em;

    }

    /**
     * @Route("/", name="recipe_index", methods={"GET"})
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $ingredientSearch=new IngredientSearch();
        $form=$this->createForm(IngredientSearchType::class,$ingredientSearch);
        $form->handleRequest($request);
        $rank=new Rank();
        $recipeSearch=new RecipeSearch();
        $form_1=$this->createForm(RecipeSearchType::class,$recipeSearch);
        $form_1->handleRequest($request);
//        $em = $this->getDoctrine()->getManager();
//        $this->em->flush();
        dump($ingredientSearch);
        $ingredientSearch=$ingredientSearch->getIngredientSearch();

        dump($recipeSearch);
        $recipeSearch=$recipeSearch->getRecipeName();

        if ($recipeSearch!=null){
//            $recipes=$this->repository->findAllSpaghetti($recipeSearch);
            //or we can use thi tips
            $recipes=$this->repository->findBy(['name'=>$recipeSearch]);

        }

        elseif ($ingredientSearch!=null){
            $recipes=$this->repository->findJoinedToIngredient($ingredientSearch);
            dump($recipes);
        }
        else{
            $recipes=$this->repository->findAllRecent();
            dump($recipes);
        }

        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipes,
            'form'=>$form->createView(),
            'searchByUser'=> 0,
            'rank'=>$rank,
            'form_1'=>$form_1->createView()
        ]);
    }

    /**
     * @Route("/new", name="recipe_new", methods={"GET","POST"})
     * @param Request $request
     * @Security("is_granted('ROLE_USER')")
     * @return Response
     */
    public function new(Request $request): Response
    {
        $user=$this->getUser();
        $recipe = new Recipe();
        $recipe->setUser($user);

        $ingredient=new Ingredient();
        $ingredient->setNameIng('banana');
        $ingredient->setRecipe($recipe);
        $recipe->addIngredient($ingredient);
        dump($recipe);

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $this->addFlash('notice','Recipe Created');
            $entityManager->flush();
            return $this->redirectToRoute('recipe_index');

        }

        return $this->render('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_show", methods={"GET","POST"})
     * @param Recipe $recipe
     * @param Request $request
     * @param RankRepository $rankRepository
     * @return Response
     */
    public function show(Recipe $recipe,Request $request,RankRepository $rankRepository): Response
    {

        $rank=new Rank();
        $form = $this->createForm(RankType::class, $rank);
        $form->handleRequest($request);
        $rank->setRankRecipe($recipe);
        $rank->setRankUser($this->getUser());
        $ingredient=$recipe->getIngredient();

        $resultat=$rankRepository->calcul($rank->getRankRecipe());
//        $resultat2=$rankRepository->countRank($rank->getRankRecipe());
//        $average=$resultat/$resultat2;

        dump($resultat);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rank);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_index');
        }

        //comment control
        $comment= new Comment();
        $formComment = $this->createForm(CommentType::class, $comment);
        $formComment->handleRequest($request);
        $comment->setCommentRecipe($recipe);
        $comment->setCommentUser($this->getUser());
        if ($formComment->isSubmitted() && $formComment->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_index');
        }
        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
            'rank'=>$rank,
            'rankRepository'=>$resultat,
            'ingredients'=>$ingredient,
            'comment'=>$comment,
            'formComment'=>$formComment->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="recipe_edit", methods={"GET","POST"})
     * @Security("is_granted('edit', recipe)", message="Access denied")
     * @param Request $request
     * @param Recipe $recipe
     * @return Response
     */
    public function edit(Request $request, Recipe $recipe): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('notice','Recipe Edited');
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_delete", methods={"DELETE"})
     * @param Request $request
     * @param Recipe $recipe
     * @Security("is_granted('delete', recipe)", message="Access denied")
     * @return Response
     */
    public function delete(Request $request, Recipe $recipe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recipe);
            $this->addFlash('notice','Recipe Deleted');
            $entityManager->flush();
        }

        return $this->redirectToRoute('recipe_index');
    }


    /**
     * @Route("/user/{username}",name="recipe_post_user")
     * @param User $userWithRecipe
     * @param RecipeRepository $recipeRepository
     * @return Response
     */
    public function userPosts(User $userWithRecipe,RecipeRepository $recipeRepository)
    {

        $html=$this->renderView('recipe/index.html.twig',[
            'recipes'=>$recipeRepository->findBy(
                ['user'=>$userWithRecipe]
            ),
            'user'=> $userWithRecipe,
            'searchByUser'=> 1

//            'posts'=>$userWithPosts->getPosts()
//        we can't use this and sort for exple with time
        ]);

        return new Response($html);
    }

}

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');" xmlns="http://www.w3.org/1999/html">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    {% if is_granted('edit',recipe) %}
        <button class="btn btn-danger" >Delete</button>
    {% endif %}

</form>

templates/recipe/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.Preparation) }}
    {{ form_row(form.imageFile) }}
<div class="col-sm 8 col-sm-offset-2" id="ingredient_list" data-prototype="{{ form_widget(form.ingredient.vars.prototype)|e('html_attr') }}">
    {% for ing in form.ingredient %}
        <div class="panel panel-warning">
            {{ form_row(ing) }}
        </div>
    {% endfor %}
</div>
<button class="m_input_champ m_inscription_submit m_no_margin_bottom j_validate">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}




{% block javascripts %}
    {#    {{ parent() }}#}
    <script>

    </script>

{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
<div class="hdr-ctnr" id="header">
    <header id="mrtn-header">

        <div class="mrtn-header__top">
            <div id="mrtn-navbar" class="search">

                <a href="{{ path('home') }}" class="mrtn-logo">
                    <img height="100" width="100" src="/images/logo/logoF.png">
                    <br>

                </a>
                <div class="separator"></div>

            </div>
            <div class="separator"></div>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mrtn-login-zone">
                <div class="mrtn-login-link connected">
                    <a >
                        <span class="mrtn-avatar--empty--xlarge mrtn-avatar--empty mrtn-hide-on-print">{{ app.user.username|first }}</span></a>
                    <div id="username" class="username">
                        <a class="un" href="{{ path('recipe_post_user',{'username':app.user.username}) }}">{{ app.user.username}}</a>
                        <br>
                        <a href="{{ path('recipe_post_user',{'username':app.user.username}) }}" class="mrtn-btn mrtn-btn-secondary mrtn-btn-text-only mrtn-btn--small">Mes recettes</a>
                        <a href="{{ path('security_logout') }}" class="mrtn-btn mrtn-btn-secondary mrtn-btn-text-only mrtn-btn--small">logOut</a>
                    </div>
                </div>
            </div>



        </div>



        <nav id="header-main-menu">
            <ul>
                <li>
                    <a class="header-main-menu__item" href="/home">Aujourd'hui</a>
                </li>
                <li>
                    <a class="header-main-menu__item " href="{{ path('recipe_index') }}">Recettes</a>
                </li>
                <li>

                    <a class="header-main-menu__item " href="{{ path('recipe_new') }}">Ajouter une recette</a>
                </li>

            </ul>
        </nav>

    </header>
</div>
<div class="div-gpt-ad-banner_atf_wrapper af-banner" id="div-gpt-ad-banner_atf_wrapper" style="text-align: center;">
    <div id="div-gpt-ad-banner_atf">
        <div id="google_ads_iframe_229683329/marmiton/organic/others/banner_atf_0__container__" style="border: 0pt none; width: 1px; height: 1px;"></div>
    </div>
</div>
<div id="content">
    <div class="hide j_overlay">

    </div>
    <div class="m_inscription_introduction_bulle">
        <div class="padded-content content-recipe">

            <h1 class="main-title ">{{ recipe.name }}</h1>
            <hr class="recipe-separator">

            <div class="recipe-author__container">
                <div class="recipe-author">
                    <div class="recipe-author__author">

                        <a href="" rel="nofollow" >
                            <span class="recipe-author__picture mrtn-avatar--empty mrtn-hide-on-print">{{ recipe.user.username|first }}</span>
                        </a>
                        {% if is_granted('edit',recipe) %}
                        <div>

                            <div class="recipe-author__more-recipe">
                            <br>
{#                                    <button href="{{ path('recipe_edit', {'id': recipe.id}) }}" class="btn btn-outline-success">edit</button><br>#}
                                    <a href="{{ path('recipe_edit', {'id': recipe.id}) }}">edit</a><br>
                                     <br>{{ include('recipe/_delete_form.html.twig') }}
                            <div>
                        {% else %}

                                    <a href="" rel="nofollow" >
                                        <span class="recipe-author__name">{{ recipe.user.username }}</span>
                                    </a>
                                    <div class="recipe-author__more-recipe">
                                <a id="recipe-author__more-recipe-link" href="{{ path('recipe_post_user',{'username':recipe.user.username}) }}">
                                    plus de recettes<i class="icon-icon_arrow_small icon-rot-180"></i></a>
                        {% endif %}
                                <br>
                                {{ recipe.time|date("d/m/Y h:m") }}



</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>




        {% if recipe.filename %}

        <div align="center" class="polaroid">
            <img src="/images/recipes/{{ recipe.filename }}" alt="5 Terre" style="width:100%">
            <div class="container">
                <p align="center">
                    {% set isLiked = recipe.getLikedBy.contains(app.user) %}

                <div class="pt-2">

                    <button style="display: {% if not isLiked %}block{% else %}none{% endif %}"
                            class="btn btn-outline-secondary btn-sm" id="like">Like
                        <span class="badge badge-light" id="likes-like">{{ recipe.getLikedBy.count }}</span>
                    </button>
                    </span>

                    <button style="display: {% if isLiked %}block{% else %}none{% endif %}"
                            class="btn btn-outline-danger btn-sm" id="unlike">Unlike
                        <span class="badge badge-light" id="likes-unlike">{{ recipe.getLikedBy.count }}</span>
                    </button>
                </div>
                </p>
            </div>
        </div>
        {% else %}
        <div align="center" class="polaroid">
            <img src="/images/recipes/NoImageFound.jpg" alt="5 Terre" style="width:100%">
            <div class="container">
                <p>
                    {% set isLiked = recipe.getLikedBy.contains(app.user) %}

                <div class="pt-2">
                    <button style="display: {% if not isLiked %}block{% else %}none{% endif %}"
                            class="btn btn-outline-secondary btn-sm" id="like">Like
                        <span class="badge badge-light" id="likes-like">{{ recipe.getLikedBy.count }}</span>
                    </button>

                    <button style="display: {% if isLiked %}block{% else %}none{% endif %}"
                            class="btn btn-outline-danger btn-sm" id="unlike">Unlike
                        <span class="badge badge-light" id="likes-unlike">{{ recipe.getLikedBy.count }}</span>
                    </button>
                </div>
                </p>
            </div>
        </div>
        {% endif %}


        <div class="separator"></div>

   <div class="jumbotron">
       <div class="align float-left" ><font color="#d2691e" > name :</font></div><br>
       <div class="align float-left">{{ recipe.name }}</div><br>
       <div class="align float-left"><font color="#d2691e" > Preparation :</font></div><br>
       <div class="align float-left">{{ recipe.preparation }}</div><br>
       <div class="align float-left"><font color="#d2691e" > Ingredients :</font></div><br>
       {% for ingredient in ingredients %}
            <div class="align float-left">-{{ ingredient.nameIng}}</div><br>
       {% endfor %}
  </div>



         {{ form_start(form) }}
            <button class="btn btn-primary">{{ button_label|default('Rank it') }}</button>
         {{ form_end(form) }}



           {{ form_start(formComment) }}
            <button class="btn btn-secondary">{{ button_label|default('+Add Comment') }}</button>
            {{ form_end(formComment) }}


        {% for comment in recipe.recipeComment %}
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <div class="w3-container">
          <div class="w3-card-4" style="width:100%">
            <div class="w3-container">
              <hr>
                <span class="mrtn-avatar--empty--xlarge mrtn-avatar--empty mrtn-hide-on-print" style="width:50%">{{ comment.commentUser.fullname|first }}</span><br>
                @{{ comment.commentUser.fullname }}:<br>
              <p>{{ comment.content }}</p><br>
              <div align="right">{{ comment.time|date("d/m/Y H:i")}}</div>
            </div>
          </div>
        </div>
        <br>
  {% endfor %}
  <br><br><br><br><br><br><br><br><br>






<footer id="mrtn-footer">
    <div class="foot-content">
        <div class="go-to-top">
            <i class="icon-rot-180 icon-icon_arrow_bottom mrtn-text-center"></i>
        </div>
        <p class="socials-items mrtn-text-center">
            <a href="https://www.pinterest.com.au/wajihg/" class="_blank social-icon-holder">
                <i class="icon-pinterest"></i>
            </a>
            <a href="https://www.facebook.com/wajih.ghali" class="_blank social-icon-holder">
                <i class="icon-facebook"></i>
            </a>
            <a href="https://www.instagram.com/wajih_ghali/" class="_blank social-icon-holder">
                <i class="icon-instagram"></i>
            </a>
            <a href="https://www.youtube.com/channel/UCnxs3iBQ0D1dabawhNobEag?view_as=subscriber" class="social-icon-holder">
                <i class="icon-youtube"></i>
            </a>
            <a href="https://assistant.google.com/services/invoke/uid/00000058f69ad4c0" class="_blank social-icon-holder">
                <i class="icon-googleassistant"></i>
            </a>
        </p>
        <div class="padded-content">
            <div class="mrtn-autopromo-ctnr">
                <a href="https://play.google.com/store/apps/details?id=com.cookware.worldcusinerecipes" class="_blank mrtn-autopromo">
                    <span class="img-iphone"><img src="https://static.afcdn.com/relmrtn/Front/Component/footerLight/assets/iPhone.png" alt="Iphone" /></span>
                    <p class="title-4">Retrouvez Hamhama où que vous soyez en téléchargeant l'application</p>
                </a>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br>


{% endblock %}

{% block javascripts %}
        {{ parent() }}


    <script>
        var likeButton = document.getElementById('like');
        var unlikeButton = document.getElementById('unlike');

        addOnClick(
            likeButton,
            unlikeButton,
            document.getElementById('likes-unlike'),
            '{{ path('likes_like', {'id': recipe.id}) }}'
        );

        addOnClick(
            unlikeButton,
            likeButton,
            document.getElementById('likes-like'),
            '{{ path('likes_unlike', {'id': recipe.id}) }}'
        );

        function switchButtons(button, oppositeButton) {
            button.disabled = false;
            button.style.display = 'none';
            oppositeButton.style.display = 'block';
        }

        function addOnClick(button, oppositeButton, likeCount, path) {
            button.addEventListener('click', function (event) {
                {% if not app.user %}
                return window.location.replace('{{ path('user_register') }}');
                {% endif %}

                button.disabled = true;

                fetch(path, {'credentials': 'include'}).then(function (response) {
                    response.json().then(function (json) {
                        likeCount.innerText = json.count;
                        switchButtons(button, oppositeButton);
                    })
                }).catch(function () {
                    switchButtons(button, oppositeButton);
                });

                event.preventDefault();
            });
        }
    </script>
{% endblock %}